### ISSUE TITLE
Cannot install with offline Cyano setup package

### ISSUE THREAD

**Issue by PolarBear520** [ontio/cyano-wallet#7]
I have tried many times with offline Cyano setup package to install it in chrome://extension page with development mode, it will setup success few times with windows, but never setup success with mac os.

**Comment by backslash47** [comment]
Hi,
I've just tried it on MacOs with no problem. Could you describe the way you tried to install it and possible error messages please?

**Comment by PolarBear520** [comment]
Hi , backslash47, 
Please see my operation below. Could you please show me your install step?

![image](https://user-images.githubusercontent.com/14345933/48240516-fd4a1a80-e40d-11e8-85d7-586385d8c339.png)
![image](https://user-images.githubusercontent.com/14345933/48240626-75b0db80-e40e-11e8-81ec-cd26d7d34bf2.png)

**Comment by backslash47** [comment]
Hi. The steps are OK. Most likely, it is due to the chrome restrictions on extension installing.

I recommend you to build it yourself from sources and then use the "Load unpacked extension" button on the built folder. 

Other option is using some CRX extractor and use the same "Load unpacked extension". 

I recommend the first option because I don't know and trust any such extractor.
